[package]
name = "manage-slack"
version = "0.1.0"
authors = ["John Stableford <john.stableford@latitudefinancial.com>"]
edition = "2018"

[dependencies]
slack_api = "0.21.0"
reqwest = "^0.9.0"
clap = "2.33"
regex = "1"
prettytable-rs = "^0.8"
