= Slack Manage CLI

Get an API KEY: https://slack.com/intl/en-gb/help/articles/215770388-Create-and-regenerate-API-tokens

== Features
* [x] "List members"
** [x] filter using regex on username or email.
** [x] Sort by EmailDomain or Username (TODO: EmailDomainReversed).
** [ ] Allow printing a tree view based on the reverse domain names.
** [ ] filter where members are inactive for more than a given time period (eg: 6 months).
* [ ] List channels a tree view based channel prefixes.
* [x] "Add members to channel" after filtering members using regex on username or email (broken because slack deprecated the channels API).
* [x] "Update usergroup members" using a list of members filtered using rege on username and email.
* [ ] List any channels where there are "external users" in channels where the name matches a pattern. EG: list all external users in channels not prefixed with `#shared-`.
* [ ] List all link:https://mantel-group.slack.com/apps/manage/custom-integrations[Incoming Hook Custom Integrations] with the details about the user who created/owns them.

== Usage

.List and filter slack members
....
slack-manage list-members \
  --token-file ./apikey.test.txt \
  --email-match email-domain.com \
  --sort-by EmailDomain
....

.List and filter using different types of filter
....
slack-manage list-members \
  --token-file="apikey.test.txt" \
  --email-match="digio.com.au" \
  --username-match="bob" \
  --email-nomatch=gmail \
  --username-nomatch="admin"
....

.Update usergroup members
....
slack-manage update-usergroup-members "DigIO" \
  --token-file ./apikey.test.txt \
  --email-match digio.com.au
....

.Invite users to channel by email
....
slack-manage add-members-to-channel channel-name --token-file ./apikey.test.txt --email-match email-domain.com
....
