/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * Contact: support@slack.com
 * Generated by: https://openapi-generator.tech
 */

/// ConversationsListErrorResponseBody : Schema for error response from conversations.list method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConversationsListErrorResponseBody {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "ok")]
    pub ok: bool,
}

impl ConversationsListErrorResponseBody {
    /// Schema for error response from conversations.list method
    pub fn new(error: String, ok: bool) -> ConversationsListErrorResponseBody {
        ConversationsListErrorResponseBody {
            error,
            ok,
        }
    }
}


