/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * Contact: support@slack.com
 * Generated by: https://openapi-generator.tech
 */

/// ConversationsListResponseBody : Schema for successful response from conversations.list method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConversationsListResponseBody {
    #[serde(rename = "channels")]
    pub channels: Vec<crate::api_client::models::OneOfconversationsListChannelconversationsListGroupconversationsListIm>,
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "response_metadata")]
    pub response_metadata: Box<crate::api_client::models::ConversationsListResponseBodyResponseMetadata>,
}

impl ConversationsListResponseBody {
    /// Schema for successful response from conversations.list method
    pub fn new(channels: Vec<crate::api_client::models::OneOfconversationsListChannelconversationsListGroupconversationsListIm>, ok: bool, response_metadata: crate::api_client::models::ConversationsListResponseBodyResponseMetadata) -> ConversationsListResponseBody {
        ConversationsListResponseBody {
            channels,
            ok,
            response_metadata: Box::new(response_metadata),
        }
    }
}


