/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * Contact: support@slack.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConversationsListConversationType {
    #[serde(rename = "public_channel")]
    PublicChannel,
    #[serde(rename = "private_channel")]
    PrivateChannel,
    #[serde(rename = "npim")]
    Npim,
    #[serde(rename = "im")]
    Im,

}

impl ToString for ConversationsListConversationType {
    fn to_string(&self) -> String {
        match self {
            Self::PublicChannel => String::from("public_channel"),
            Self::PrivateChannel => String::from("private_channel"),
            Self::Npim => String::from("npim"),
            Self::Im => String::from("im"),
        }
    }
}

impl Default for ConversationsListConversationType {
    fn default() -> ConversationsListConversationType {
        Self::PublicChannel
    }
}




