/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReactionsGetSuccessSchemaTempOneof01 {
    #[serde(rename = "channel")]
    pub channel: String,
    #[serde(rename = "message")]
    pub message: Box<crate::api_client::models::ObjsMessage>,
    #[serde(rename = "ok")]
    pub ok: crate::api_client::models::DefsOkTrue,
    #[serde(rename = "type")]
    pub _type: Type,
}

impl ReactionsGetSuccessSchemaTempOneof01 {
    pub fn new(channel: String, message: crate::api_client::models::ObjsMessage, ok: crate::api_client::models::DefsOkTrue, _type: Type) -> ReactionsGetSuccessSchemaTempOneof01 {
        ReactionsGetSuccessSchemaTempOneof01 {
            channel,
            message: Box::new(message),
            ok,
            _type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "message")]
    Message,
}

impl Default for Type {
    fn default() -> Type {
        Self::Message
    }
}

