/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ReactionsGetSuccessSchema : Schema for successful response from reactions.get method



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReactionsGetSuccessSchema {
    #[serde(rename = "temp_oneof_01", skip_serializing_if = "Option::is_none")]
    pub temp_oneof_01: Option<Box<crate::api_client::models::ReactionsGetSuccessSchemaTempOneof01>>,
    #[serde(rename = "temp_oneof_02", skip_serializing_if = "Option::is_none")]
    pub temp_oneof_02: Option<Box<crate::api_client::models::ReactionsGetSuccessSchemaTempOneof02>>,
    #[serde(rename = "temp_oneof_03", skip_serializing_if = "Option::is_none")]
    pub temp_oneof_03: Option<Box<crate::api_client::models::ReactionsGetSuccessSchemaTempOneof03>>,
}

impl ReactionsGetSuccessSchema {
    /// Schema for successful response from reactions.get method
    pub fn new() -> ReactionsGetSuccessSchema {
        ReactionsGetSuccessSchema {
            temp_oneof_01: None,
            temp_oneof_02: None,
            temp_oneof_03: None,
        }
    }
}


