/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UsersIdentitySchemaTempOneof02User {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "image_192")]
    pub image_192: String,
    #[serde(rename = "image_24")]
    pub image_24: String,
    #[serde(rename = "image_32")]
    pub image_32: String,
    #[serde(rename = "image_48")]
    pub image_48: String,
    #[serde(rename = "image_512")]
    pub image_512: String,
    #[serde(rename = "image_72")]
    pub image_72: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl UsersIdentitySchemaTempOneof02User {
    pub fn new(id: String, image_192: String, image_24: String, image_32: String, image_48: String, image_512: String, image_72: String, name: String) -> UsersIdentitySchemaTempOneof02User {
        UsersIdentitySchemaTempOneof02User {
            id,
            image_192,
            image_24,
            image_32,
            image_48,
            image_512,
            image_72,
            name,
        }
    }
}


