/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UsersIdentitySchemaTempOneof01User {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl UsersIdentitySchemaTempOneof01User {
    pub fn new(email: String, id: String, name: String) -> UsersIdentitySchemaTempOneof01User {
        UsersIdentitySchemaTempOneof01User {
            email,
            id,
            name,
        }
    }
}


