/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UsersIdentitySchemaTempOneof01 : Schema for 'identity.basic,identity.email' scopes



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UsersIdentitySchemaTempOneof01 {
    #[serde(rename = "ok")]
    pub ok: crate::api_client::models::DefsOkTrue,
    #[serde(rename = "team")]
    pub team: Box<crate::api_client::models::UsersIdentitySchemaTempOneof00Team>,
    #[serde(rename = "user")]
    pub user: Box<crate::api_client::models::UsersIdentitySchemaTempOneof01User>,
}

impl UsersIdentitySchemaTempOneof01 {
    /// Schema for 'identity.basic,identity.email' scopes
    pub fn new(ok: crate::api_client::models::DefsOkTrue, team: crate::api_client::models::UsersIdentitySchemaTempOneof00Team, user: crate::api_client::models::UsersIdentitySchemaTempOneof01User) -> UsersIdentitySchemaTempOneof01 {
        UsersIdentitySchemaTempOneof01 {
            ok,
            team: Box::new(team),
            user: Box::new(user),
        }
    }
}


