/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * Contact: support@slack.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UsersListMemberProfile {
    #[serde(rename = "avatar_hash")]
    pub avatar_hash: String,
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "display_name_normalized")]
    pub display_name_normalized: String,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "first_name", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "image_24", skip_serializing_if = "Option::is_none")]
    pub image_24: Option<String>,
    #[serde(rename = "image_32", skip_serializing_if = "Option::is_none")]
    pub image_32: Option<String>,
    #[serde(rename = "image_48", skip_serializing_if = "Option::is_none")]
    pub image_48: Option<String>,
    #[serde(rename = "image_72", skip_serializing_if = "Option::is_none")]
    pub image_72: Option<String>,
    #[serde(rename = "image_192", skip_serializing_if = "Option::is_none")]
    pub image_192: Option<String>,
    #[serde(rename = "image_512", skip_serializing_if = "Option::is_none")]
    pub image_512: Option<String>,
    #[serde(rename = "image_1024", skip_serializing_if = "Option::is_none")]
    pub image_1024: Option<String>,
    #[serde(rename = "image_original", skip_serializing_if = "Option::is_none")]
    pub image_original: Option<String>,
    #[serde(rename = "last_name", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[serde(rename = "real_name", skip_serializing_if = "Option::is_none")]
    pub real_name: Option<String>,
    #[serde(rename = "real_name_normalized")]
    pub real_name_normalized: String,
    #[serde(rename = "skype", skip_serializing_if = "Option::is_none")]
    pub skype: Option<String>,
    #[serde(rename = "status_emoji")]
    pub status_emoji: String,
    #[serde(rename = "status_text")]
    pub status_text: String,
    #[serde(rename = "team")]
    pub team: String,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl UsersListMemberProfile {
    pub fn new(avatar_hash: String, display_name: String, display_name_normalized: String, real_name_normalized: String, status_emoji: String, status_text: String, team: String) -> UsersListMemberProfile {
        UsersListMemberProfile {
            avatar_hash,
            display_name,
            display_name_normalized,
            email: None,
            first_name: None,
            image_24: None,
            image_32: None,
            image_48: None,
            image_72: None,
            image_192: None,
            image_512: None,
            image_1024: None,
            image_original: None,
            last_name: None,
            phone: None,
            real_name: None,
            real_name_normalized,
            skype: None,
            status_emoji,
            status_text,
            team,
            title: None,
        }
    }
}


